### ISSUE TITLE
gulp build errors

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/DeepSeeWeb#12]
````
C:\temp\DeepSeeWeb>gulp
[17:19:06] Warning: gulp version mismatch:
[17:19:06] Global gulp is 3.9.1
[17:19:06] Local gulp is 3.9.0
C:\temp\DeepSeeWeb\gulpfile.js:144
        append += `
                  ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Users\eduard\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\eduard\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\eduard\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
```

**Comment by eduard93** [comment]
Can't reproduce on latest, closing.
