### ISSUE TITLE
Libs missing

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/DeepSeeWeb#94]
Got this build error

```PS C:\temp\DeepSeeWeb> npm rebuild minify
PS C:\temp\DeepSeeWeb> gulp
[17:43:59] Using gulpfile C:\temp\DeepSeeWeb\gulpfile.js
[17:43:59] Starting 'lint'...
[17:43:59] Finished 'lint' after 10 ms
[17:43:59] Starting 'minify'...
[17:43:59] 'minify' errored after 114 ms
[17:43:59] Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (C:\temp\DeepSeeWeb\node_modules\gulp-useref\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)```

**Comment by eduard93** [comment]
1. Deleted `node_modules`
2, Ran `npm install && gulp`

It compiled, but I'm unable to find:

- /src/lib/tinycolor-min.js
- /src/lib/angularjs-color-picker.min.js

They are also unavailable in [repo](https://github.com/intersystems-ru/DeepSeeWeb/tree/master/src/lib).
